stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-frontend:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker build --build-arg "BACKEND_URL=https://$CI_PROJECT_NAME.vwprg.mylab.th-luebeck.de" -t $IMAGE_TAG/frontend:frontend-latest frontend/.

build-backend:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker build -t $IMAGE_TAG/backend:backend-latest backend/.

deploy-everything:
  stage: deploy
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker push $IMAGE_TAG/frontend:frontend-latest
    - docker push $IMAGE_TAG/backend:backend-latest