stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE

build-frontend:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg "BACKEND_URL=https://$CI_PROJECT_NAME-backend.vwprg.mylab.th-luebeck.de" -t $IMAGE_TAG/frontend:frontend-temp frontend/.
    - docker push $IMAGE_TAG/frontend:frontend-temp

build-backend:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG/backend:backend-temp backend/.
    - docker push $IMAGE_TAG/backend:backend-temp

deploy-everything:
  stage: deploy
  only:
    variables:
      - $CI_COMMIT_REF_SLUG == "main"
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - crane tag $IMAGE_TAG/frontend:frontend-temp frontend-latest
    - crane tag $IMAGE_TAG/backend:backend-temp backend-latest