version: '3'
services:
  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'vwprog-mariadb:/var/lib/mysql'
    networks:
      - vwprog-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:mariadb
    ports:
      - "8000:80"
    environment:
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
    networks:
      - vwprog-net
  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - './frontend:/usr/app'
    networks:
      - vwprog-net
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/app'
    depends_on:
      - mariadb
    networks:
      - vwprog-net
networks:
  vwprog-net:
    driver: bridge
volumes:
  vwprog-mariadb:
    driver: local